### ISSUE TITLE
Are there any zero-shot classification results?

### ISSUE THREAD

**Issue by invictus717** [microsoft/LLM2CLIP#4]
Are there any zero-shot classification results?  In addition, are there more VLM evaluation results? Current experimental results seem not convincing enough.

**Comment by invictus717** [comment]
Meanwhile, have you tried to scale up the vision encoder? The main results are conducted with ViT-L.

**Comment by invictus717** [comment]
Thanks in advance!

**Comment by Yif-Yang** [comment]
Thanks for comments.


- We will soon release more LLM2CLIP models, including larger versions of EVA02 ViT-E, InternVL, and SIgLIP.
- Our current improvement in ImageNet zero-shot results is not significant, as we believe that single-word classification is not a task that LLMs excel at. However, we will soon organize various downstream classification task datasets and update the results. 
- More VLM results will be updated in an upcoming paper, focusing on how to use LLM2CLIP to further enhance verious VLM's performance.

**Comment by invictus717** [comment]
LLM2CLIP does not bring out significant improvements on imagenet-1k only or all these zero-shot benchmarks?  

Have you ever measured the average caption length between your method and vanilla EVA-02-CLIP? In my opinion, longer text captions do not always bring out improvements.

It's reasonable to improve the performances of VLMs on the SQA and Wizwiz benchmarks while it's strange to drop the performances on the fundamental benchmarks such as MME.

**Comment by invictus717** [comment]
"We utilized the ShareCaptioner-modified CC-3M dataset (Zheng et al., 2024; Chen et al.,2023), which provides both original captions and augmented dense captions for each image, for contrastive learning."

May I ask how much the performance improvement by the re-captioned high-quality CC-3M dataset? Is the target of such reception to improve the caption length? Then LLM2CLIP can pretrain the ViT with longer and detailed captions and then significantly improve the retrieval performances. Is there an ablation study on the average caption length for LLM2CLIP?

Thank you so much for the prompt response!

**Comment by Yif-Yang** [comment]
We haven’t specifically tested it, and the improvement on ImageNet isn’t very clear. My guess is that we used a large number of dense captions, which might lead the model to favor more complex text. However, we’ve already observed through experiments that ImageNet performance is highly correlated with data volume, which could be related to the word distribution used during alignment. For our alignment and LLM fine-tuning, we only used 15 million data points. In the next version, we plan to increase the training data for LLM2CLIP by tens of times very soon, so we will re-evaluate at that point.

The improvement from using long or dense captions for CLIP is quite limited. LongCLIP (https://arxiv.org/abs/2403.15378) and DCI (https://arxiv.org/abs/2312.08578) focus exactly on this issue. The problem here is that the original CLIP text encoder lacks the ability to understand such detailed information or to handle longer text lengths. Meanwhile, LLM2CLIP still performs exceptionally well and leads on fully short datasets; you can refer to Table 5 in our paper for more details.

**Comment by invictus717** [comment]
Thanks for the insightful response, I look forward to the next version of LLM2CLIP!
